### ISSUE TITLE
Plugin shows Error after Reoad

### ISSUE THREAD

**Issue by JustAnotherIssue** [ncains/homebridge-petwalk#6]
Hey there,
does someone have a clue why it fails with an ARP error?
The plugin is fresh installed, ever since it shows the same - the door itself is fully operational with this IP.
Thx for any tip
Stefan

**LOG:**
[9.9.2022, 13:46:13] [PetwalkPlugin] Error: Command failed: arp -n 192.168.220.232

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'arp -n 192.168.220.232'
}

**CONFIG**:
{
    "doors": [
        {
            "ipAddress": "192.168.220.232",
            "displayName": "LiniGate",
            "doorOpenDelayTimer": 90000
        }
    ],
    "statusUpdateFrequency": 500,
    "platform": "PetwalkPlugin"
}

**Comment by JustAnotherIssue** [comment]
... found out that is is - maybe - Windows related. I am running homebridge on a virtual Win2019 server and it looks like the command arp -n does not exist in Windows.

Could you please help to resolve this @ncains ?

Thanks a lot
